### ISSUE TITLE
Wheelmap corrupts OSM tagging if a tag contains &

### ISSUE THREAD

**Issue by Nakaner** [sozialhelden/wheelmap-open-source#5]
If a tag contains `&` and you edit this POI via Wheelmap web interface, Wheelmap replaces `&` by `&#38;` afterwards. At the second time you edit this object via Wheelmap, Wheelmap replaces `&#38;` by `&#38;#38;` at OSM data. In other words, every time a Wheelmap user modifies an object which has a tag which contains `&`, this `&` is changed to `&#38;`. This changes OSM data (or, in other words, corrupts them).

Example: If I go to Sachsenheim station, click on "Edit" and afterwards on "Save" (without editing anything) [`operator=DB Station&Service AG` is replaced by `operator=DB Station&#38;Service AG`](https://www.openstreetmap.org/node/247669894/history).

It seems that every OSM tag can be corrupted this way. [I have fixed this type of data corruption today in whole Germany (search data via Overpass API and fix it object by object).](https://www.openstreetmap.org/changeset/29748180)

The bug only occurs if the data is edited by logged-in users. Edits done anonymously [do not cause these data corruptions](https://www.openstreetmap.org/node/2656117800/history). It seems that only the web interface and neither the Android nor the iOS app is affected.

**Comment by christoph-buente** [comment]
Hi @Nakaner,

thx for the report. We had this issue a few years back and fixed it. But yeah, encoding problem occur randomly.

As we are using rosemary as OSM API client, the bug is likely to happen in there.
https://github.com/sozialhelden/rosemary

Cheers Christoph

**Comment by Nakaner** [comment]
@christoph-buente 
shall I report it there?

I have used Firefox 36.0 at Arch Linux. I don't know what browser other users used when the bug occured.

**Comment by christoph-buente** [comment]
I think it is not browser dependent. The data is supposed to be utf-8 encoded, but as & is an html_entity it might be some funny use case. So yes, i think it is a good idea to report it at rosemary issues.
