### ISSUE TITLE
Searching switches language back to German

### ISSUE THREAD

**Issue by Rondom** [sozialhelden/wheelmap-open-source#6]
Steps to reproduce:
1. Go to http://wheelmap.org/en/
2. Search for a place by typing in for example "Stockholm" and pressing Enter

Actual:
Results appear, language switches to German

Expected:
Results appear, language stays English

**Comment by chocoladisco** [comment]
Can easily be switched by changing the following on the landing page:
```
<form method="GET" action="http://wheelmap.org/search">
	<fieldset>
		<input name="q" placeholder="Search for a place" type="text">
		<input class="btn-jeans" value="Suchen" type="submit">
	</fieldset>
</form>
```

to:
```
<form method="GET" action="/search">
	<fieldset>
		<input name="q" placeholder="Search for a place" type="text">
		<input class="btn-jeans" value="Suchen" type="submit">
	</fieldset>
</form>
```

I have no clue however in which of the many files to change it and my Ruby knowledge is pretty much non existant.

**Comment by Rondom** [comment]
This is the WordPress part of the site. So I guess it is not surprising that we cannot find it in this repository. The source for this does not seem to be available.

I am not sure, what the long-term strategy regarding the WordPress site is.

**Comment by lennerd** [comment]
Yep, you are right. The Wordpress part of the Wheelmap is not part of this repository as the Rails application only handles the routing to it.

But never the less thank you for your bug report! We will have a look, how we can fix this in the blog. I give this to our Wordpress experts. :wink:
